<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.2" />
    <ProjectReference Include="../StudentEscrow.Application/StudentEscrow.Application.csproj" />
  </ItemGroup>
</Project>
