// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentEscrow.Infrastructure.Persistence;

#nullable disable

namespace StudentEscrow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(StudentEscrowDbContext))]
    [Migration("20261002065603_WalletProofAndMockKyc")]
    partial class WalletProofAndMockKyc
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentEscrow.Domain.Kyc.KycSubmission", entity =>
                {
                    entity.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    entity.Property<string>("DocumentReference")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    entity.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    entity.Property<string>("ReasonCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    entity.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("datetimeoffset");

                    entity.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    entity.Property<string>("SelfieReference")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    entity.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    entity.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(29)
                        .HasColumnType("nvarchar(29)");

                    entity.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("datetimeoffset");

                    entity.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    entity.Property<Guid>("WalletLinkId")
                        .HasColumnType("uniqueidentifier");

                    entity.HasKey("Id");

                    entity.HasIndex("UserId");

                    entity.HasIndex("WalletLinkId")
                        .IsUnique();

                    entity.ToTable("KycSubmissions", (string)null);
                });

            modelBuilder.Entity("StudentEscrow.Domain.Users.User", entity =>
                {
                    entity.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    entity.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    entity.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    entity.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    entity.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    entity.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    entity.HasKey("Id");

                    entity.HasIndex("NormalizedEmail")
                        .IsUnique();

                    entity.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("StudentEscrow.Domain.Wallets.WalletChallenge", entity =>
                {
                    entity.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    entity.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("nvarchar(42)");

                    entity.Property<long>("ChainId")
                        .HasColumnType("bigint");

                    entity.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    entity.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("datetimeoffset");

                    entity.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    entity.Property<string>("Nonce")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    entity.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("datetimeoffset");

                    entity.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    entity.HasKey("Id");

                    entity.HasIndex("UserId", "ExpiresAt");

                    entity.ToTable("WalletChallenges", (string)null);
                });

            modelBuilder.Entity("StudentEscrow.Domain.Wallets.WalletLink", entity =>
                {
                    entity.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    entity.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("nvarchar(42)");

                    entity.Property<long>("ChainId")
                        .HasColumnType("bigint");

                    entity.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("datetimeoffset");

                    entity.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    entity.HasKey("Id");

                    entity.HasIndex("Address")
                        .IsUnique();

                    entity.HasIndex("UserId")
                        .IsUnique();

                    entity.ToTable("WalletLinks", (string)null);
                });

            modelBuilder.Entity("StudentEscrow.Domain.Kyc.KycSubmission", entity =>
                {
                    entity.HasOne("StudentEscrow.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    entity.HasOne("StudentEscrow.Domain.Wallets.WalletLink", null)
                        .WithMany()
                        .HasForeignKey("WalletLinkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentEscrow.Domain.Wallets.WalletChallenge", entity =>
                {
                    entity.HasOne("StudentEscrow.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentEscrow.Domain.Wallets.WalletLink", entity =>
                {
                    entity.HasOne("StudentEscrow.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
