// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentEscrow.Infrastructure.Persistence;

#nullable disable

namespace StudentEscrow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(StudentEscrowDbContext))]
    [Migration("20261002053750_InitialUsers")]
    partial class InitialUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentEscrow.Domain.Users.User", entity =>
                {
                    entity.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    entity.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    entity.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    entity.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    entity.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    entity.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    entity.HasKey("Id");

                    entity.HasIndex("NormalizedEmail")
                        .IsUnique();

                    entity.ToTable("Users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
